### ISSUE TITLE
TypeError with "nuxt generate"

### ISSUE THREAD

**Issue by manastalukdar** [manastalukdar/manastalukdar.github.io#89]
Error:

```
TypeError: Cannot assign to read only property 'base' of object '#<Object>'
    at W (server.js:1:7914)
    at W (server.js:1:7898)
    at W (server.js:1:7898)
    at W (server.js:1:7898)
    at W (server.js:1:7898)
    at new We (server.js:1:749132)
    at Wo.use (server.js:1:768689)
    at new Wo (server.js:1:768382)
    at Go (server.js:1:770226)
    at hi (server.js:1:774607)
    at async e.default (server.js:1:775704)
```

Links:

- https://github.com/nuxt-community/vuetify-module/issues/268

**Comment by manastalukdar** [comment]
[blog_metadata.zip](https://github.com/manastalukdar/manastalukdar.github.io/files/4084857/blog_metadata.zip)

**Comment by manastalukdar** [comment]
1. Get _blog_metadata.json_ file from [here](https://github.com/manastalukdar/manastalukdar.github.io/files/4084857/blog_metadata.zip).
2. Under the `website/static` folder, create a new folder called `blogdata`.
3. Under `blogdata` folder create a new folder called `metadata` and copy the _blog_metadata.json_ from step 1 into this new `website/static/blogdata/metadata` folder.
4. Copy the folder (along with all sub-folders) `website/blog/2019` into `website/static/blogdata`. `website/static/blogdata` should now have 2 subfolders: `2019` and `metadata`.
